#!/usr/bin/env bash

RETRIES_COUNT=3
RETRIES_TIMEOUT=120

function retry {
  local retries=$1
  local wait=$2
  shift 2

  local count=0
  until "$@"; do
    exit=$?
    count=$(($count + 1))
    if [ $count -lt $retries ]; then
      echo "Retry $count/$retries exited $exit, retrying in $wait seconds..."
      sleep $wait
    else
      echo "Retry $count/$retries exited $exit, no more retries left."
      return $exit
    fi
  done
  return 0
}

function check_and_run {
  if [ -e /etc/letsencrypt/.certbot.lock ]; then
    echo 'Another instance of Certbot is already running.'
    return 1
  else
    certbot $@
  fi
}

retry $RETRIES_COUNT $RETRIES_TIMEOUT check_and_run $@
